name: Check

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "node_version=$(cat .github/node.version)" >> $GITHUB_ENV
      - name: "use node v${{ env.node_version }}"
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.12
      - uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Lint check
        run: pnpm lint
      - name: Format check
        run: pnpm format
      - name: Unit & Integration tests
        run: pnpm test
      - name: Smoke & Acceptance tests
        run: |
          pnpm build-storybook --quiet
          pnpx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "pnpx http-server storybook-static --port 6006 --silent" \
            "pnpx wait-on tcp:127.0.0.1:6006 && pnpm test-storybook"
      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm test:e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
